version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - INFLUX_URL=http://18.189.176.144:8086
      - INFLUX_TOKEN=PmSv00l0gu1zAL53Ih4xPcNrDj9lqRHikLmgAqqtWzADg_H_19YiN0OBXY5P4GkPICZhxwokjZYF-9c_fhCaCA==
      - INFLUX_ORG=aproposdrive
      - INFLUX_BUCKET=rd
      - PORT=5000
      - GRAFANA_URL=http://18.189.176.144:3000
      - GRAFANA_API_KEY=eyJrIjoiMjcwYTRlNjkzM2RjYTI0YTJiZjE5MDUzMGY3ZjM1NTQ2ODMzMTE5ZiIsIm4iOiJpbmZsdXhkYiIsImlkIjo3NTQyNjV9
      - LOKI_USERNAME=raysanandkumar
      - NODE_ENV=development
    volumes:
      - backendvol:/data/db
    restart: always
volumes:
  backendvol:
